### ISSUE TITLE
Light not adapting as expected

### ISSUE THREAD

**Issue by cooper7012** [basnijholt/adaptive-lighting#418] opened 2023-01-14 00:55 UTC
#### Description:
I just installed the integration and set it up. It appears to be working, however sun set was at 5:55pm it’s currently 7:51pm and the lights are at 38% I would expect the lights to be at my min brightness by now. Not unless I’m misunderstanding how it all works.

I don’t have any errors messages.

Is it possible that the time zone or location is incorrect?

**Comment by Takaszi** [comment] 2023-01-16 15:51
Hello, I have the same. I bought a GLEDOPTO 12W RGB CCT Zigbee 3.0 bulb E26 E27 Pro. The bulb changes color and brightness, but never goes down to 0% brightness and does not start from that. I don't know what settings to make.

**Comment by ontje-dev** [comment] 2023-01-17 22:18
hi, as far as i can see this is the expected behavior. i created some sensors to track the sun, brighness and color temperature:
![image](https://user-images.githubusercontent.com/4669933/213024194-31750753-1245-4e62-80ad-753371c175bb.png)
this is the brightness:
![image](https://user-images.githubusercontent.com/4669933/213024498-ebbff17a-fcea-451d-8d97-757f38976d75.png)

my sleep_mode is active from 22:00 to 06:00, this explains the bigger changes at this times.

as you can see, the brightness will still be at 100% at sunset and slowly decrease to your minimum brightness value over the next hours.

**Comment by bluecube22** [comment] 2023-01-18 00:15
I came here with the same question and I think it was a misunderstanding about when the minimum brightness is reached. I expected it to reach `min_brightness` right when it was fully dark outside but it actually dims gradually throughout whole the night.

**Comment by Takaszi** [comment] 2023-01-18 16:23
Hello. So this is not a behavior consistent with the observed from the point of my residence. It is a sine wave. If so, how, in addition to manual control, to force working hours? Setting the sunrise time and sunset time manually?
My next question is about the brightness of the light bulb. In RGB mode it is much darker. In temperature control mode, it shines three times brighter. However, there is no gradual change in this mode.

**Comment by MarkHofmann11** [comment] 2023-01-31 17:15
> I came here with the same question and I think it was a misunderstanding about when the minimum brightness is reached. I expected it to reach `min_brightness` right when it was fully dark outside but it actually dims gradually throughout whole the night.

That was my assumption as well, but sounds like that isn't the case.  Maybe this is more of a feature request than an issue - not sure.  

I would like to be able to configure min-max brightness to work together with sunrise/sunset if possible.  Obviously there would be around a 30/60 minute buffer since sunset doesn't mean it is pitch dark outside instantly.

**Comment by Takaszi** [comment] 2023-01-31 18:50
My expectation is similar, I want to be able to configure min and max brightness to work together with sunrise/sunset if possible. Of course, a buffer of around 30/60 minutes would be necessary, as sunset doesn't mean it's immediately dark outside. If you can ask for such functionality, I'm also in it.

**Comment by SteffanDonal** [comment] 2023-02-03 11:21
+1 to this and following this thread. I'd love to see some way to customise the curve involved in blending "day" and "night" presets for temp/brightness!

**Comment by SteffanDonal** [comment] 2023-02-05 22:23
The problem is that the current implementation assumes you want to reach minimum brightness at midnight and maximum brightness at sunrise.
The offset parameters are a poor option for adjusting this as they _also_ impact the times that midnight & noon fall. 

My suggestions:
1. Add new, or switch the existing offsets to work without affecting midnight/midday calculations. Clamp them within "event boundaries" so you don't break the math.
2. Add "dimming duration", "finish dimming X time after sunset", "brightening duration", and "finish dimming X time after sunrise" options.

This should let us get the exact behaviour we're looking for - controlling the start/end of the window around sunrise/sunset for brightness transition times.

PS. I believe the current behaviour WRT colour temp is fine; I don't need to customise this personally. Brightness, however... Yeah, I want it darker faster, please 😅

**Comment by th3w1zard1** [comment] 2023-03-12 21:48
Is this issue not fixed with the addition of `max_sunrise_time`, `min_sunset_time`, `sunset_time`, and `sunrise_time` variables?

**Closed** 2023-04-01 15:56 UTC
Labels: kind/bug, need/author-input
