### ISSUE TITLE
Manual overruling not working anymore 

### ISSUE THREAD

**Issue by rbovenkampclearict** [basnijholt/adaptive-lighting#331] opened 2022-09-02 19:14 UTC
#### Version information:
Latest version. It did work a few versions before but I don’t remember that version number

#### Description:
Manual overrule by dimming a light with a button doesn’t work. The brightness is set to the the adaptive light level after a few seconds / minutes. 

I reinstalled the adaptive lightning script but unfortunately it still doesn’t work.

**Comment by basnijholt** [comment] 2022-09-02 19:15
Can you what the last version is that it worked for you?

That will help me tremendously in finding the bug.

**Comment by rbovenkampclearict** [comment] 2022-09-02 19:21
Unfortunately I can’t remember the version number but I installed it 2 weeks ago. And I’m quite sure that that was the last version at that time. It than works for a week or so, and a few days ago I saw there were some updates which i installed. At that time it doesn’t work anymore.

**Comment by rbovenkampclearict** [comment] 2022-09-02 19:22
Can I checks some logs to check this?

**Comment by basnijholt** [comment] 2022-09-02 20:32
You can use HACS to install older versions and figure out where the problems don't occur anymore.

**Comment by mirkolenz** [comment] 2022-09-09 20:43
@basnijholt I installed `Adaptive Lighting` a few days ago and experienced the same issue. In my case, I set `take_over_control: false` and created a custom automation that calls `adaptive_lighting.set_manual_control` if certain criteria are met. I stumbled upon this issue when researching for issues that are related to mine. Could this (in my case) be caused by the combination of disabling `take_over_control` and then wanting to call `set_manual_control` anyway?

**Comment by fpschrisiom** [comment] 2022-09-13 09:21
I also have this issue. .17 and latest. Had to completely remove the integration for now as any light turned off by the physical switch comes back on after 20 seconds.
It could've equally been caused by an update to HA

**Comment by heytcass** [comment] 2022-09-19 22:40
Also having the same issues. Have noticed that if I uncheck the min/max/sleep brightness checkboxes in the configuration and click submit, the next time I open Configure they're checked again. Even with the Adapt Brightness switches turned off, the brightness still seems to get adjusted.

**Comment by basnijholt** [comment] 2022-09-19 23:02
If anyone can pinpoint which version does not exhibit this problem, it will allow me to fix the bug.

**Comment by estevez-dev** [comment] 2022-10-25 14:30
Ok, so I have Adaptive Lighting 1.1.0

It sets to control a light group and I change the brightness of this group with a remote directly bound to a group. `take_over_control ` is on and I tried with and without `detect_non_ha_changes`. Most of the time I change the brightness with a remote  - `manual_control` of a responsive switch stays empty. Even when the change is significant.

`manual_control` was enabled only once during my experiments and I was not able to determine why.

No errors or warnings in HA log.

@basnijholt, please, let me know if you need some more information.

**Comment by rykzon** [comment] 2022-10-30 18:07
v1.1.1

for me it appears both manually changing lights and even manually setting manual_control=true doesn't work as expected and the lights switch back to adaptive after a few seconds

**Comment by rykzon** [comment] 2022-10-30 20:27
I'm pretty sure in my case it is this issue   #304 
I had setup AL with one instance and linked it to multiple devices. I then manually changed a subset of those devices which got reverted by AL. I will try to confirm by setting up AL instances for each group.

**Comment by msl2424** [comment] 2022-11-16 03:14
I have Philips Hue lights throughout my home connected to a Hue hub. Most are controlled by a Lutron Aurora Smart Bulb Dimmer Switch for adjusting the brightness, and turning on and off. Take_over_control and detect_non_ha_changes do not work at all for me with these bulbs and switches. Is there any solution?

**Comment by doylejg** [comment] 2022-11-21 02:45
I am using the L530E bulb and I have the same issue with `detect_non_ha_changes` not working (I believe I tested making changes from HA and those changes stick). Specifically, I am making changes with Google Assistant, so HA would only know when it pulls the new data from the bulb.

**Comment by th3w1zard1** [comment] 2023-04-01 05:10
This will most likely fixed by #486

**Comment by th3w1zard1** [comment] 2023-04-08 12:43
This has been fixed by 1.11.0

**Closed by th3w1zard1** 2023-04-08 12:43 UTC
Labels: kind/bug, duplicate, status/in-progress, status/done+waiting-for-review
