### ISSUE TITLE
Tuya lights turn back on even after command to turn off

### ISSUE THREAD

**Issue by drguitarum2005** [basnijholt/adaptive-lighting#425] opened 2023-02-01 04:52 UTC
I have the adaptive lighting working well for various lights such as Wyze, Sengled, and various others. I have one Cree LED in HA that gets turned off with all the others (via a Goodnight automation) but about 10 seconds later it turns right back on. It doesn't behave like this if I disable my one Adaptive Lighting integration. Is it possible that somehow this one is NOT respecting the rules about outside changes?

**Comment by bluecube22** [comment] 2023-02-03 17:25
Possible duplicate of https://github.com/basnijholt/adaptive-lighting/issues/377

In the Adaptive Lighting configuration, try setting `interval` to smaller value than `transition` and `sleep_transition` and restarting Home Assistant.

**Comment by diamant-x** [comment] 2023-02-08 15:44
I have the same with my nanoleafs and a couple of Ikeas.


> Possible duplicate of #377
> 
> In the Adaptive Lighting configuration, try setting `interval` to smaller value than `transition` and `sleep_transition` and restarting Home Assistant.

I'm using the default integration configuration from github readme. Is such a configuration a faulty one then (as interval is higher than the other two)?
![image](https://user-images.githubusercontent.com/7346338/217578616-3b99ce7a-725b-416b-b034-267e31d7e47b.png)

**Comment by drguitarum2005** [comment] 2023-02-08 15:55
> Possible duplicate of #377
> 
> In the Adaptive Lighting configuration, try setting `interval` to smaller value than `transition` and `sleep_transition` and restarting Home Assistant.

This seems to work. Thanks!

**Comment by drguitarum2005** [comment] 2023-03-16 14:47
Unfortunately it’s back to happening as I’ve been fighting it for several nights now. Only solution so far has been to remove that light from the adaptive lighting.

**Comment by th3w1zard1** [comment] 2023-04-10 11:18
this should be solved in 1.10.1

**Closed by th3w1zard1** 2023-04-10 11:18 UTC
Labels: need/author-input
