### ISSUE TITLE
Don't send RGB value when color temperature is being changed and vice versa

### ISSUE THREAD

**Issue by CorvetteCole** [basnijholt/adaptive-lighting#117] opened 2021-05-16 04:48 UTC
with my custom esphome based lights, adaptive lighting sends a setting like this
```
[00:46:58][D][light:265]: 'Computer Light' Setting:
[00:46:58][D][light:278]:   Brightness: 7%
[00:46:58][D][light:282]:   Color Temperature: 500.0 mireds
[00:46:58][D][light:287]:   Red=100%, Green=100%, Blue=100%
[00:46:58][D][light:304]:   Transition Length: 45.0s
```

This confuses the code on my light to whether it should set color temp or rgb and ends up with either both or one or the other. Can we avoid sending the RGB values when we are in color temp mode?

**Comment by RubenKelevra** [comment] 2021-07-31 15:32
I don't think this should happen. Do you have RGB mode on or off?

**Comment by CorvetteCole** [comment] 2021-07-31 16:05
RGB mode is off

**Comment by basnijholt** [comment] 2021-07-31 19:56
Those logs you post it don’t seem familiar to me. Is this not another component that is logging it? 

It might be possible that adaptive lighting is not sending the RGB value at all but that the logger of that component is always logging the RGB value.

**Comment by CorvetteCole** [comment] 2021-08-03 14:43
@basnijholt this is actually the logger from my esphome RGBW controller. For reference, when I change the color temperature through the home assistant interface, no RGB values are sent. I'm not certain this software is the culprit, but I'm not sure what the difference is between how Adaptive Lighting and how Home Assistant temperature control sends lighting commands. I can try to do some further investigating soon if you want

**Comment by th3w1zard1** [comment] 2023-04-01 05:49
Hi @CorvetteCole. Are you still having this issue with the latest adaptive lighting version 1.7.0?

**Comment by CorvetteCole** [comment] 2023-04-01 14:19
Unfortunately I've changed my hardware so I no longer have this issue. I still have the old controller, I can give it a look if you want

**Comment by th3w1zard1** [comment] 2023-04-01 14:29
Sure! If the issue is present, I'm sure someone else is having the issue and we should debug this.

**Comment by th3w1zard1** [comment] 2023-04-06 21:01
I believe this is fixed in 1.10.1

**Comment by CorvetteCole** [comment] 2023-04-06 22:16
I'd like to apologize and warn in advance, I have a long backlog right now (busy!) so this might take a few weeks to get to. Hopefully can do it this weekend but we'll see

**Comment by th3w1zard1** [comment] 2023-04-06 22:22
No worries at all, this is your project after all and of course you can do it at your own leisure. I'm just noting the issues where I believe there was code introduced that could potentially fix the issue.

hass was updated significantly since this was posted and the bitfield `supported_features` was completely deprecated by `supported_color_modes` which adaptive lighting now uses.

**Comment by basnijholt** [comment] 2023-08-06 21:13
In the spirit of cleaning up the issues here, I will close this one. Feel free to reopen if it turns out this problem still exists.

**Closed by basnijholt** 2023-08-06 21:13 UTC
Labels: kind/bug, need/author-input, prio, effort/hours, actionable, need/team-analysis, need/community-input
