### ISSUE TITLE
XY color values do not match color temperature

### ISSUE THREAD

**Issue by JRaeuber** [basnijholt/adaptive-lighting#93] opened 2021-02-24 17:34 UTC
It seems like adaptive lightning does not match color temperature correctly to xy color values.
For example 2700 K result in in x: 0.527; y: 0.386 which is about 1800 K and far away from the black body curve.

For testing purposes I set min and max color temperature to 2700 K and read the resulting values in the devices in zigbee2mqtt.
Or does adaptive lightning uses RGB values and zigbee2mqtt converts them wrong to xy values?
I am using zigbee2mqtt with an IKEA TRADFRI led bulb.

**Comment by MikaelHoogen** [comment] 2021-03-05 17:06
This has been an issue even with circadian lightning. HA seems to have some strange conversion thats completely off. This makes the xy function useless. :(

**Comment by JRaeuber** [comment] 2021-03-05 22:38
So maybe it would be better if there is an option in adaptive lightning that values can be send directly as correctly calculated xy colorvalues?
Would be great to have the cheap rgb IKEA lights supported, right now they are not usable at all with adaptive lightning.

**Comment by MikaelHoogen** [comment] 2021-03-06 11:36
Yes I agree. I have IKEA rgb lights and this issue is preventing me to use this integration. I have my IKEA bulbs in deconz and if you send a command with colo temperature to deconz it does the calculation correctly. The problem is that that the bulb is missing the supported feature so adaptive lightning are sending xy commands. So i'm stuck with using circadian lightning, there you can force color temperature and it's perfect.

I opened an issue earlier where i asked for the option to force color temperature even if the bulb doesnt support it:
https://github.com/basnijholt/adaptive-lighting/issues/59

**Comment by Heronimonimo** [comment] 2021-05-20 19:51
Here also having this issue. The conversion from color temperature to XY in HA seems to be quite a bit off. It is very visible when next to my other Yeelight bulbs. The Ikea bulb has a purple glow to it and the temperatures are off.

@basnijholt Would it be possible to let adaptive-lighting calculate XY values and get an option to force using these?

**Comment by jaddel** [comment] 2021-11-28 00:26
this would be great 1+

**Comment by mikedrawback** [comment] 2021-12-22 04:23
I have noticed that my TRADFRI bulbs turn very red while adaptive lighting is on. Then if I turn the adaptive lighting switch off and back on they change to the correct color. Is this related to this issue? Why would adaptive lighting behave differently when first turning the switch on compared to the periodic change?

**Comment by mikedrawback** [comment] 2021-12-27 19:30
It seems like adaptive lighting is noticing that the colors are off because when it turns them red I noticed that they subsequently get switched to manual control.

**Comment by RubenKelevra** [comment] 2022-01-09 20:03
This will be fixed in v2 as individual color temperature and brightness corrections are part of it (https://github.com/basnijholt/adaptive-lighting/issues/124).

Color temperature to XY color will be reviewed as well, so please keep this ticket open until this is fixed in v2

**Comment by th3w1zard1** [comment] 2023-04-01 05:30
I was modifying the xy <--> color temp conversion code today and noticed that this seemed to be a Home Assistant issue.

What's more, finding a reliable algorithm to convert RGB values to color temp was very difficult. Everything on google talked about color_temp --> RGB but not the reverse.

I also noticed that my light has two different attributes for color_xy.

![image](https://user-images.githubusercontent.com/2219836/229267430-491b6428-1bc9-4c31-a914-d5cde7212f4b.png)

Only the ones marked `color` were accurate during conversions.

**Closed** 2023-04-06 21:02 UTC
Labels: kind/bug, popularity-high, actionable, kind/enhancement, status/in-queue, related-to-v1
