### ISSUE TITLE
ULID must be 26 characters (HA 2023.4.)

### ISSUE THREAD

**Issue by Coder84619** [basnijholt/adaptive-lighting#548] opened 2023-04-06 14:43 UTC
#### Version information: 
1.9.1
HAOS 2023.4

#### Description:

Logger: homeassistant.components.recorder.core
Source: components/recorder/models/context.py:15
Integration: Recorder ([documentation](https://www.home-assistant.io/integrations/recorder), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+recorder%22))
First occurred: 7:42:30 AM (2 occurrences)
Last logged: 7:42:31 AM

Error while processing event EventTask(event=<Event call_service[L]: domain=light, service=turn_on, service_data=entity_id=light.office, transition=1.0, brightness=255, color_temp_kelvin=3200>): ULID must be 26 characters
Error while processing event EventTask(event=<Event state_changed[L]: entity_id=light.office, old_state=<state light.office=on; min_color_temp_kelvin=2000, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=500, supported_color_modes=[<ColorMode.COLOR_TEMP: 'color_temp'>, <ColorMode.XY: 'xy'>], color_mode=color_temp, brightness=255, color_temp_kelvin=3184, color_temp=314, hs_color=(27.547, 52.114), rgb_color=(255, 183, 122), xy_color=(0.479, 0.38), is_hue_group=True, hue_scenes={'Morning', 'Evening'}, hue_type=room, lights={'Office rear left', 'Office front left', 'Office Floor Lamp', 'Office front right', 'Office desk LED strip', 'Office rear right'}, dynamics=False, icon=mdi:light-recessed, friendly_name=Office Ceiling Lights, supported_features=LightEntityFeature.TRANSITION|FLASH @ 2023-04-06T07:42:30.802765-07:00>, new_state=<state light.office=on; min_color_temp_kelvin=2000, max_color_temp_kelvin=6535, min_mireds=153, max_mireds=500, supported_color_modes=[<ColorMode.COLOR_TEMP: 'color_temp'>, <ColorMode.XY: 'xy'>], color_mode=color_temp, brightness=255, color_temp_kelvin=3205, color_temp=312, hs_color=(27.518, 51.595), rgb_color=(255, 183, 123), xy_color=(0.478, 0.379), is_hue_group=True, hue_scenes={'Morning', 'Evening'}, hue_type=room, lights={'Office rear left', 'Office front left', 'Office Floor Lamp', 'Office front right', 'Office desk LED strip', 'Office rear right'}, dynamics=False, icon=mdi:light-recessed, friendly_name=Office Ceiling Lights, supported_features=LightEntityFeature.TRANSITION|FLASH @ 2023-04-06T07:42:30.802765-07:00>>): ULID must be 26 characters
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 825, in _guarded_process_one_task_or_recover
    self._process_one_task_or_recover(task)
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 836, in _process_one_task_or_recover
    return task.run(self)
  File "/usr/src/homeassistant/homeassistant/components/recorder/tasks.py", line 281, in run
    instance._process_one_event(self.event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 944, in _process_one_event
    self._process_non_state_changed_event_into_session(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/core.py", line 953, in _process_non_state_changed_event_into_session
    dbevent = Events.from_event(event)
  File "/usr/src/homeassistant/homeassistant/components/recorder/db_schema.py", line 276, in from_event
    context_id_bin=ulid_to_bytes_or_none(event.context.id),
  File "/usr/src/homeassistant/homeassistant/components/recorder/models/context.py", line 15, in ulid_to_bytes_or_none
    return ulid_to_bytes(ulid)
  File "src/ulid_transform/_ulid_impl.pyx", line 22, in ulid_transform._ulid_impl._ulid_to_bytes
ValueError: ULID must be 26 characters

**Comment by th3w1zard1** [comment] 2023-04-06 18:13
duplicate of https://github.com/basnijholt/adaptive-lighting/issues/493

**Closed** 2023-04-06 18:13 UTC
Labels: kind/bug, duplicate

**Comment by basnijholt** [comment] 2023-04-06 20:53
Closed as not planned, but in reality, this problem shouldn't pop up anymore.

Our context ids are now 26 chars.

Update to 1.10.1.
