### ISSUE TITLE
Scenes not turning on properly due to AL

### ISSUE THREAD

**Issue by turkomano** [basnijholt/adaptive-lighting#314] opened 2022-08-18 21:46 UTC
I am facing an issue, I have to enable scenes once, twice or even thrice for my scene to properly activate. This is due to AL taking over control, although take_over_control is enabled. There should be a way to turn on lights without triggering AL (f.e. an attribute to the light.turn_on service).

Currently I have disabled AL to avoid this problem, because it was extremely annoying to turn on scenes.

**Comment by callumgare** [comment] 2023-02-27 15:25
I also have this issue and I think it would be solved if https://github.com/basnijholt/adaptive-lighting/issues/416 was implemented

**Comment by th3w1zard1** [comment] 2023-03-18 03:07
This straight up shouldn't ever happen, if this is happening this needs to be set as kind/bug and the devs would need you to post your log and configuration.

`take_over_control` is supposed to ignore any light.turn_on calls when not called with an empty payload (i.e `brightness` or `color_temp` is set in the `light.turn_on` call).

**Comment by th3w1zard1** [comment] 2023-03-22 07:29
Duplicate of #2. You need to turn lights on before changing their brightness/rgb_color/color_temp/whatever (two separate calls) in order to fire the manual control event.

**Closed by th3w1zard1** 2023-03-22 07:29 UTC
Labels: need/triage, kind/enhancement

**Comment by basnijholt** [comment] 2023-08-06 01:07
I am implementing an option `adapt_only_on_bare_turn_on` which instantly triggers `manual_control` when turning on with brightness or color in PR https://github.com/basnijholt/adaptive-lighting/pull/709.

Enabling this will make sure AL doesn't take over when setting a scene.

**Comment by callumgare** [comment] 2023-08-06 01:28
@basnijholt brilliant! I’d love that! Thanks very much 😊
