### ISSUE TITLE
[Feature Request] Operate color temp and brightness separately

### ISSUE THREAD

**Issue by psbankar** [basnijholt/adaptive-lighting#29] opened 2020-10-27 18:33 UTC
AFAIK, right now, the changes in brightness and color temp take place at the same time. But the problem is that with MQTT lights, both the attributes are set to change at the same time. Some MQTT smart bulbs can take only one attribute change at a time. So, for me only the color temp changes or the brightness. Both attributes never change. If you could add an option to change the attributes separately, it would be great.

**Comment by basnijholt** [comment] 2020-10-27 19:06
Is this true for all MQTT lights?

**Comment by basnijholt** [comment] 2020-10-27 19:39
@psbankar could you try the latest commit, I've added a `separate_turn_on_commands` option.

**Comment by basnijholt** [comment] 2020-10-27 19:42
This is a duplicate of https://github.com/basnijholt/adaptive-lighting/issues/16.

**Comment by nickg90** [comment] 2020-10-27 19:49
I think psbankar means for his light, when adaptive-lighting sends the command to the lights [60% brightness, 1000k], it only picks up the 60% brightness and the 1000k does not get set. It may fix the issue to have send the [60% brightness] setting and THEN [1000k] setting which will allow the lights to react to each new setting seperatly

**Comment by basnijholt** [comment] 2020-10-27 19:51
@nickg90, a right, I misremembered what you were asking.

**Comment by psbankar** [comment] 2020-10-27 19:52
Yes, @nickg90 got it right. In the latest commit, the light on command is triggering before the usual color temp and brightness command so it didn't work for me.

**Comment by basnijholt** [comment] 2020-10-27 19:54
Could you tell me the exact sequence of commands that you need?

**Comment by psbankar** [comment] 2020-10-27 20:00
As @nickg90 said, I need the brightness and color_temp/RGB commands split up. i.e you could use a separate command for setting the brightness and separate for color_temp/RGB.

**Comment by basnijholt** [comment] 2020-10-27 20:54
Yes, that is exactly what I implemented.

Could you try it?

**Comment by psbankar** [comment] 2020-10-28 05:42
Ok, I figured out what was going wrong for me. Because of transition, color_temp, and brightness attributes, three separate commands were being sent. And because of the transition command, the light was turning on at full brightness again. I have fixed the issue for me by adding a condition to ignore the transition command.

**Comment by basnijholt** [comment] 2020-10-28 18:00
That shouldn't be needed, I can fix it.

Are you able to do?
```
- service: light.turn_on
  data:
    color_temp: ...
    entity_id: light.yolo]
    transition: ...
- service: light.turn_on
  data:
    brightness: ...
    entity_id: light.yolo
    transition: ...
```

**Comment by psbankar** [comment] 2020-10-28 18:06
Yes those commands work

**Comment by basnijholt** [comment] 2020-10-28 18:07
OK then I should change the implementation.

The only thing you need to do separately is the color and brightness?

**Comment by psbankar** [comment] 2020-10-28 19:09
Yes, that's right. You can combine transition with color and brightness so only two commands are sent.

**Comment by basnijholt** [comment] 2020-10-30 11:10
I've made the changes accordingly, now it sends one `light.turn_on` for
- brightness (and optionally white_value) + transition
- color + transition

**Comment by basnijholt** [comment] 2020-11-01 16:17
I consider this solved. Please ping me here if this is not the case.

**Closed by basnijholt** 2020-11-01 16:17 UTC
Labels: feature-request
