### ISSUE TITLE
Lights won't dim

### ISSUE THREAD

**Issue by YourAvgBear** [basnijholt/adaptive-lighting#335] opened 2022-09-07 22:41 UTC
I have Adaptive Lighting installed and working, but the lights won't dim.  They stay at whatever brightness is set as the max brightness in AL.  I'm using a dozen KAUF wifi bulbs that I haven't had any issues with outside of this.  I have tried various combinations of "separate turn on commands" and toggling the change brightness and change color switches to no avail.

**Comment by pesbob** [comment] 2022-10-02 08:31
Same problem here.
I manually set the sunset at 18:00:00 and the brightness at 1%,
But it only dim down to ca 46%.
:-(

**Comment by tetsuo55** [comment] 2022-10-28 09:21
I can confirm this issue.
Despite using 1%  the lights are dimmed to 20% instead

**Comment by th3w1zard1** [comment] 2023-03-22 05:29
Closing due to the broad topic and lack of information in OP. Please post your configuration, and debug logs following the instructions in the readme if you'd like help from others diagnosing your issues.

**Closed by th3w1zard1** 2023-03-22 05:29 UTC
Labels: kind/bug, need/triage
