### ISSUE TITLE
adaptive_lighting.manual_control event not fired when making changes outside of Home Assistant 

### ISSUE THREAD

**Issue by MarvinSchenkel** [basnijholt/adaptive-lighting#34] opened 2020-10-31 19:34 UTC
Hi,

Not sure if this is a bug or a feature, but it seems that the `adaptive_lighting.manual_control` event is not fired whenever I make changes to my lights using my IKEA TRADFRI remote. I do expect this to happen, so I can turn off adaptive lights whenever I manually adjust my lights using a remote control.

I am using the following configuration:
```
name: bedroom
lights:
  - light.bedside_left
  - light.bedside_right
detect_non_ha_changes: true
interval: 5
```

**Comment by basnijholt** [comment] 2020-10-31 19:52
From the docs
> Whether to detect state changes and stop adapting lights, even not from light.turn_on. Needs take_over_control to be enabled.

**Comment by MarvinSchenkel** [comment] 2020-10-31 19:58
Also from the docs
`take_over_control boolean (optional, default: true`

I'll try to explicitly set this to true and see if it makes a difference, but I did expect this to be enabled by default.

**Comment by basnijholt** [comment] 2020-10-31 19:59
Oh, a very good point. That is indeed the default. I am AFK now but will look into this when I get home.

**Comment by basnijholt** [comment] 2020-11-01 12:42
Do you perhaps use ZHA?

**Comment by basnijholt** [comment] 2020-11-01 20:54
Due to lights not always doing what you're telling them to do, lights only become marked as manually controlled whenever to update periods have happened.

It should happen right here:
https://github.com/basnijholt/adaptive-lighting/blob/17ac3951240a65e75e79a548b85d50d7319d9f9b/custom_components/adaptive_lighting/switch.py#L1327-L1334

**Comment by MarvinSchenkel** [comment] 2020-11-01 21:12
I am not using ZHA. My tradfri lights are connected to home assistant via WiFi using the ikea hub. The remote just controls the lights and is not connected to home assistant. Even after changing the brightness from 0-100 in increments using just the remote, it's still not reporting a manual change in home assistent. I'd say this should pass the significant changes condition, so I don't see why it isn't.

**Comment by basnijholt** [comment] 2020-11-01 21:29
Perhaps `homeassistant.update_entity` isn't implemented correctly for the IKEA hub.

How long does is take for the brightness changes to show up in Home Assistant after using the remote?

And could you use the `homeassistant.update_entity` service immediately after making a change with the remote and see if the light has the correct state?

**Comment by MarvinSchenkel** [comment] 2020-11-01 21:42
The brightness changes show up nearly instantly if I open the app and change the brightness with my remote. I'm afk now, but I'll try manually calling update entity. Or can be assume it's been correctly implemented, as the changes show up in the mobile app?

**Comment by milutt** [comment] 2020-11-03 11:08
Hi,

I am experiencing the same issue. I use Hue lights integrated to HA via Hue integration.
Changes from HA activate manual_control, but changes from Hue app or remote are not picked up.
I even tried executing homeassistant.update_entity right after change, does not help.

config:
```adaptive_lighting:
- name: "Living Room"
  lights:
    - light.living_room
  min_brightness: 30
  take_over_control: true
  detect_non_ha_changes: true

**Comment by basnijholt** [comment] 2020-11-03 14:26
Could either one share logs? See https://github.com/basnijholt/adaptive-lighting#having-problems

That is the only way I can find out what the problem is.

**Comment by milutt** [comment] 2020-11-03 15:49
Here is my log. Scenario:
turn on light (AL adjusted brightness)
decrease brightness in Hue app (AL restored initial brightness)
decrease brightness 2nd time in Hue app (AL restored initial brightness again)
[home-assistant.log](https://github.com/basnijholt/adaptive-lighting/files/5482396/home-assistant.log)

**Comment by milutt** [comment] 2020-11-08 13:18
I found culprit in my environment. I have two AL switches, default and living_room.
Both must have been applied to the same light entity, conflicting each other.
After disabling default switch, everything works fine.
Is there a way to list light entities that AL switch is controlling (including dynamically applied ones)?

**Comment by basnijholt** [comment] 2020-12-19 15:42
@MarvinSchenkel, I have the suspicion that this issue has the same cause as https://github.com/basnijholt/adaptive-lighting/issues/39 which I have just fixed.

Could you perhaps try again and report whether the issue is solved?

**Comment by RicardoCst** [comment] 2021-03-02 09:50
I have the same issue, adaptive_lighting.manual_control doesnt fire I was listening using the dev tools and waited 90 seconds and I switched the light using a hue dimmer, I got nothing. im using 2x hue bulbs.

**Comment by RicardoCst** [comment] 2021-03-02 14:12
It seems that using the hue dimmer the manual control event wont fire, and it will just reset to its adaptive light state.

**Comment by basnijholt** [comment] 2021-03-02 16:33
> It seems that using the hue dimmer the manual control event wont fire, and it will just reset to its adaptive light state.

Are you using a Philips Hue hub? Or via Deconz/ZHA?

**Comment by RicardoCst** [comment] 2021-03-02 20:28
hue

**Comment by RicardoCst** [comment] 2021-03-03 09:30
#54

**Comment by RubenKelevra** [comment] 2021-07-31 12:17
@MarvinSchenkel Can you reconfirm this issue for HA 2021.7.4?

**Comment by RubenKelevra** [comment] 2022-01-08 00:44
This went stale.

**Closed by RubenKelevra** 2022-01-08 00:44 UTC
Labels: kind/bug, need/author-input, not actionable, need/team-verification, need/team-effort-estimate
