### ISSUE TITLE
Multiple errors in log

### ISSUE THREAD

**Issue by anoblet** [basnijholt/adaptive-lighting#145] opened 2021-07-02 12:43 UTC
I'm receiving multiple errors in the log:

```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/adaptive_lighting/switch.py:1220
Integration: Adaptive Lighting
First occurred: July 1, 2021, 5:59:50 PM (66 occurrences)
Last logged: 8:08:07 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1220, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'
```

I do have a motion sensor setup that I may believe could be the culprit.

Any suggestions on debugging?

**Comment by RubenKelevra** [comment] 2021-07-31 15:27
@basnijholt can you help here?

**Comment by basnijholt** [comment] 2021-08-01 14:21
I believe this happens when using areas. @anoblet  could you confirm this? I believe I've seen this in some other issue too which I've tagged as bug.

**Comment by anoblet** [comment] 2021-08-06 21:56
I do have separate areas that are controlled differently with regards to adaptive lighting.

**Comment by barberio** [comment] 2021-08-08 02:27
I also saw this error, and have identified that it is caused by automations calling light.turn_on or light.turn_off against a device. A work around is to change this to a call against an entity instead.

Possibly caused by the control detection code expecting to always see an entity?

(It may also be occurring with areas being turned on and off, but I don't use areas.)

**Comment by systemcrash** [comment] 2021-08-15 13:29
Yeah, I get this:
```
ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/adaptive_lighting/switch.py", line 1228, in turn_on_off_event_listener
    entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'
```

When I trigger an automation. 

Configure like so:
Action: Call service: light.turn_off: pick device(s).... : transition, 5 sec
Action: Call service: light.turn_on: pick device(s).... : transition, 5 sec

no properties set when I use turn_on (except transition)

**Comment by pimw1** [comment] 2021-08-25 08:51
I've got exactly the same issue.

**Comment by RubenKelevra** [comment] 2022-06-15 02:07
> I also saw this error, and have identified that it is caused by automations calling light.turn_on or light.turn_off against a device. A work around is to change this to a call against an entity instead.
> 
> Possibly caused by the control detection code expecting to always see an entity?
> 
> (It may also be occurring with areas being turned on and off, but I don't use areas.)

Ah!

Thanks for the analysis!

This means it will be fixed by this goal in the v2 roadmap:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886261

**Closed by RubenKelevra** 2022-06-15 02:07 UTC
Labels: kind/bug, popularity-high, need/team-analysis, need/team-effort-estimate, related-to-v1
