### ISSUE TITLE
correction of brightness % on different lamps (+color temperature) 

### ISSUE THREAD

**Issue by RubenKelevra** [basnijholt/adaptive-lighting#124] opened 2021-05-24 02:17 UTC
I got some different lights and they all got different brightness values for the same percentage.

Some lights are still very bright when running at 1% while others are barley on.

Additionally the reflection of light in the room is very difficult based on indirect or direct light and how a light source is spread out like LED strips vs bulbs.

It would be nice if the user would be able to run through a setup which just runs all the lights against each other with various settings to correct different brightness and color temperature interpretations of those lights.

The user could be asked which light eliminates brighter, while running through random values with two lights, until the light curve is bent and the user responds over the whole range that they are equally bright.

Same goes for the color temperature.

**Comment by Varjo1** [comment] 2021-06-06 15:24
Yep, per-light color temperature and brightness offsets would be AMAZING.

**Comment by RubenKelevra** [comment] 2021-06-24 10:26
Here is the issue of different color temperatures.

Left is a somewhat cheap RGBCCT lightstrip for zigbee. On the right is a super expensive Yeelight high quality RGB light strip from yeelight.

Both are configured to show the same color temperature - which obviously isn't the case. 

![Screenshot_20210624-122204629](https://user-images.githubusercontent.com/614929/123247625-60b5e780-d4e7-11eb-9e2c-6f1cfcbf67ea.jpg)

_The picture (on my AMOLED screen) look exactly as real life._

**Comment by RubenKelevra** [comment] 2022-01-08 01:01
I'm currently in the process of doing version 2. This will be added/fixed.

Keep this ticket open until you can verify that it's properly working in the upcoming version 2.

**Comment by tamueller** [comment] 2022-02-01 09:04
I think there are two levels for this feature: One ist to just set the max/min Brightness and Temperature per Lamp, and the other one to set the whole shape per Lamp. I would really love to get the first thing rather soon - while I think individual shapes are quite complex to implement and also to configure for the user.

Is there any workaround for the first thing? I thought about creating two instances of adaptive Lightning with different settings, but that doesn't seem to work.

**Comment by basnijholt** [comment] 2023-08-06 21:16
This is a great suggestion, however, not in scope at the moment because such an application is hard to build into HA.

Also, this seems to be a duplicate of https://github.com/basnijholt/adaptive-lighting/issues/102 (which is only for brightness though).

So in the spirit of keeping a keep issue log, I will close this one because the other is older.

**Closed by basnijholt** 2023-08-06 21:16 UTC
Labels: kind/feature, popularity-high, actionable, status/in-queue
