### ISSUE TITLE
Lights turn on by themself

### ISSUE THREAD

**Issue by marithpl** [basnijholt/adaptive-lighting#246] opened 2022-01-12 10:41 UTC
#### Description:
I've noticed a problem with 3 of my bulbs (Hue via Hue Bridge, Ikea via Deconz) that lights sometimes turn on by themselves.
I was looking for a reason for about 1 month and yesterday I turned off Adaptive Lightning Integration for this lights.
After about 24 hour I didn't noticed this problem. So it should be related with this integration.

Usually logs of my bulbs looks like this:
<img width="368" alt="Zrzut ekranu 2021-12-13 o 20 44 10" src="https://user-images.githubusercontent.com/25366097/149124529-2edec089-190d-4275-85e2-68171551a56f.png">
In translations automation turn on a bulb,
after that turning off because of state_changed
and after that turn on light by service light.turn_on

To be sure I still using the same automation before and after disabling integration.

Is anyone have the same problem or also have a solution for that?

Im really missing the sleep mode when bulbs are on 1% brightness.

And here is my automation:
```
alias: 🏃 [Piętro] Turn on light on motion (v 2.0 with bug)
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.presence_79
    to: 'on'
    from: 'off'
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.lightlevel_80
            below: '100'
        sequence:
          - service: light.turn_on
            data: {}
            entity_id: light.color_temperature_light_18
          - wait_for_trigger:
              - platform: state
                entity_id: binary_sensor.presence_79
                from: 'on'
                to: 'off'
                for:
                  hours: 0
                  minutes: 0
                  seconds: 10
          - service: light.turn_off
            data: {}
            entity_id: light.color_temperature_light_18
    default:
      - service: light.turn_off
        target:
          entity_id: light.color_temperature_light_18
mode: restart
```

**Comment by maartenlandman89** [comment] 2022-01-22 09:06
I've got the same problem. When i turn off all light, some of them are turning on by themself after a few seconds. I have Ikea lights with Zigbee2MQTT and Conbee 2. 
In the logs i can't find a reason for it..

**Comment by markunca** [comment] 2022-01-27 07:54
The same for me started from yesterday with version 1.0.15. Two of my 20+ bulbs doing it.

**Comment by marithpl** [comment] 2022-01-27 07:59
Good to see that I'm not alone.
Guys what bulbs usually turn on by themselves? In my case it's Ikea GU10, Ikea Floalt, Gledopto RGBCCT Controller

**Comment by markunca** [comment] 2022-01-27 09:18
Ikea Floalt, different types of Ikea Bulbs (E27 LEDs) with Ikea Gateway and remotes

**Comment by marithpl** [comment] 2022-01-27 09:29
In my case I have bulbs connected to Hue Bridge or Deconz/Conbee II

**Comment by BadCo-NZ** [comment] 2022-01-28 07:08
I am also having issues with lights turning back on.

I am using Shelly duo's and Shelly Dimmers.

**Comment by confucius78** [comment] 2022-01-29 00:07
Same here. All ikea lights with ikea bridge

**Comment by Shin-nn** [comment] 2022-01-29 19:56
I have the same issue, do not have much time do dig inside, it looks like adaptive lightning has old information about light status. Just quickly checked the code - in case of philips hue, it is possible to send just a change color command without turning on, but Home assistant has no support for that... would it be solution?

**Comment by confucius78** [comment] 2022-01-31 07:08
Over the weekend I tested a bit further and found the issue even occurs with the integration switched off!

I created an automation which switches off the integration and then the lights. Even after running that, several lights are switching back on.

**Comment by BadCo-NZ** [comment] 2022-01-31 09:06
> Over the weekend I tested a bit further and found the issue even occurs with the integration switched off!
> 
> I created an automation which switches off the integration and then the lights. Even after running that, several lights are switching back on.

Did you still have the automation ```Adaptive lighting: reset manual_control after 1 hours``` enabled?

**Comment by confucius78** [comment] 2022-01-31 09:26
Sorry, not sure what you mean by that. There are no other automations running that control the lights or adaptive lighting, unless there is something running in the background through the integration.

To clarify my earlier comment: after the integration and (after that) the lights are switched off, the lights come back on for a minute or so. As if there are a couple of adjustments still in the queue which are then executed. I don't have time to dig through the code, but it seems there is no on/off check prior to issuing a brightness/color update. I think someone mentioned this before, but at least Ikea lights switch on when brightness is adjusted, even without sending an explicit on command.

After switching off a second time the lights do stay off when the integration is disabled.

This is an issue I have noticed before, so it is not related to that, but FYI currently running HA latest beta 2022-02.

**Comment by BadCo-NZ** [comment] 2022-01-31 09:32
> Sorry, not sure what you mean by that. There are no other automations running that control the lights or adaptive lighting, unless there is something running in the background through the integration.
> 
> To clarify my earlier comment: after the integration and (after that) the lights are switched off, the lights come back on for a minute or so. As if there are a couple of adjustments still in the queue which are then executed. I don't have time to dig through the code, but it seems there is no on/off check prior to issuing a brightness/color update. I think someone mentioned this before, but at least Ikea lights switch on when brightness is adjusted, even without sending an explicit on command.
> 
> After switching off a second time the lights do stay off when the integration is disabled.
> 
> This is an issue I have noticed before, so it is not related to that, but FYI currently running HA latest beta 2022-02.

[See here](https://github.com/basnijholt/adaptive-lighting#automation-examples)

**Comment by confucius78** [comment] 2022-01-31 10:44
If you refer to the automation example in the readme: no that is not running

**Comment by jabbink** [comment] 2022-02-22 17:02
Briefly tried to debug this and it seems like https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L1486 checks for the transition used to `turn_off`

change your calls to
```yaml
- service: light.turn_off
  data:
    transition: 0
  target:
    entity_id: [entity]
```
and see if it's fixed for you. Tested it a couple of times for me, and so far the lights stay off

**Comment by ItsEcholot** [comment] 2022-04-07 06:45
I have this exact issue as well IKEA lights with Deconz & Conbee 2

**Comment by EndEffected** [comment] 2022-04-07 20:05
i have the same issue with philips light trough Zigbee2mqtt with a conbee2

**Comment by CeeWeasel** [comment] 2022-04-12 12:22
I'm having this same issue too. Given that the recent update refers to a change in the Hue API made especially for HA, I assume that it broke something that this listens to.

Messages like this keep appearing in the logs, and I'm assuming it is why the lights keep turning on:
```
2022-04-12 08:12:37 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Computer Area: Detected an 'off' → 'on' event for 'light.computer_area_hue' with context.id='900b17185530b3dc69059e27476af9f5'
2022-04-12 08:12:37 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/adaptive_lighting/switch.py", line 959, in _light_event
if await self.turn_on_off_listener.maybe_cancel_adjusting(
File "/config/custom_components/adaptive_lighting/switch.py", line 1474, in maybe_cancel_adjusting
id_turn_on = turn_on_event.context.id
AttributeError: 'NoneType' object has no attribute 'context'
```

**Comment by BadCo-NZ** [comment] 2022-04-17 11:36
Does anyone have an alternative to Adaptive-Lighting?

This bug is ruining the wife approval factor, but I do enjoy the auto dimming.

**Comment by xnyhps** [comment] 2022-04-17 18:44
I've been using this integration with a number of Tradfri lights (via the Tradfri hub integration). I had this issue as well: I'd turn off the lights, and then a few seconds later some of the lights would turn back on again.

I had `separate_turn_on_commands` enabled (because Tradfri lights apparently don't support transitioning both the brightness and temperature at the same time). Transition time is set to 45 seconds and interval to 90.

As a test I've turned off `separate_turn_on_commands` and since then this bug has (almost completely) stopped happening. I suspect the delayed change used for `separate_turn_on_commands` still fires if the lights turned off in between. As the interval is equal to twice the transition time, there would be a high chance that it still needs to adjust the other part.

It still happened a few times, but those times the state shown in HA was also out of sync with the hub. Restarting the hub was necessary to get that fixed again. So, this may not be a complete fix, but I do think it might fix it in some common cases.

**Comment by BadCo-NZ** [comment] 2022-05-15 05:08
> The same for me started from yesterday with version 1.0.15. Two of my 20+ bulbs doing it.

@markunca at you implying this wasn't happening before 1.0.15? I might roll hack and see if that fixes it temporarily.

**Comment by markunca** [comment] 2022-05-16 07:47
Honestly, I disabled this plugin till yesterday as it was not possible to run it day-to-day. Yesterday, I again activate it and for now, with everyting in HA up-to-date I cannot see happening this bug. I will monitor it and if it will happen again, will share it here.

**Comment by BadCo-NZ** [comment] 2022-05-16 08:19
> > The same for me started from yesterday with version 1.0.15. Two of my 20+ bulbs doing it.
> 
> @markunca at you implying this wasn't happening before 1.0.15? I might roll hack and see if that fixes it temporarily.

Can confirm, this bug exists in 1.14 as well.

**Comment by hACKrus** [comment] 2022-05-17 12:16
Solved this issue by clean reinstall of 1.0.14. Works well with Hue and Zigbee2MQTT lamps.
@markunca, @BadCo-NZ, thanks for idea.

**Comment by basnijholt** [comment] 2022-05-18 02:12
@hACKrus, are you sure it is really fixed? @BadCo-NZ mentioned that the bug exists in the older version too.

I have compared the older code to the new code and cannot think of anything that can cause this problem.

**Comment by BadCo-NZ** [comment] 2022-05-18 02:40
I don't know what @hACKrus did for a "clean install" but I just redownloaded the older version through the HACS menu.

**Comment by jabbink** [comment] 2022-05-24 11:03
Another way to "fix" this is to turn on `only_once` by the way, from the basic debugging I did on this, it seems as if some trigger to update the light with time passing is not properly stopped when the light gets turned off in the meantime, turning it back on when it wants to adjust the brightness.

Have/had this issue with Tradfri lights.

**Comment by groovee** [comment] 2022-05-31 18:50
Hi Guys,
I have the same with Ikea Tradfri bulbs and Deconz (Conbee II). Two rooms, 6 bulbs in one integration (motion sensor to turn one / timer to turn off).

I'm not sure, but I suppose that light goes up randomly  during first 1-120 secs after being turned off (it did not ever turned on in the middle of the night).

I already tested configuring each bulb separately as well as in groups.
Current settings: 0 for all transitions, 900 interval, only_one & separate_turn_on enabled (I tested multiple combinations).
In my case, it is enough to toggle "Adaptive Lightning ON/OFF" to "solve" the issue.

**Comment by markunca** [comment] 2022-05-31 19:01
I can confirm that when I downgraded to 1.0.14 with below mentioned process shared by @hACKrus it is now working for me seamlessly.

Clean install =

Delete Adaptive Lightning Integration
Delete Adaptive Lightning in HACS
Reboot HA
Install Adaptive Lightning in HACS
Reboot HA
Added and configured Adaptive Lightning Integration for one room.
It's really fixed for me.

Thanks!

**Comment by BadCo-NZ** [comment] 2022-06-14 01:57
> I can confirm that when I downgraded to 1.0.14 with below mentioned process shared by @hACKrus it is now working for me seamlessly.
> 
> Clean install =
> 
> Delete Adaptive Lightning Integration Delete Adaptive Lightning in HACS Reboot HA Install Adaptive Lightning in HACS Reboot HA Added and configured Adaptive Lightning Integration for one room. It's really fixed for me.
> 
> Thanks!

Confirmed this has also worked for me now. No lights have turned back on for over a week :)

**Comment by MizterB** [comment] 2022-06-14 11:51
I followed the clean install and downgrade process, but found that when I downgraded, the adaptive switch attributes were no longer available (although the switch functionality was OK).  Because I rely on those attributes for automations, I had no choice but to upgrade to the latest revision again.  Once I upgraded, all functionality returned to normal, and I am no longer seeing the random lights turning on.   Long story short...for me, a clean reinstall seems to have solved the problem - not necessarily the downgrade.

**Comment by RubenKelevra** [comment] 2022-06-15 02:21
Hey @marithpl, @maartenlandman89, @MizterB, @groovee, @markunca, @BadCo-NZ, @jabbink, @confucius78, @hACKrus, @xnyhps, @EndEffected, @ItsEcholot, @Shin-nn,

This may be two unrelated issues reported here in one ticket.

That lights may turn on again after a short period is a known race condition, which will be fixed with this goal on the roadmap v2:

https://github.com/basnijholt/adaptive-lighting/discussions/291#discussioncomment-2886261

_(See my comment on that, for the explanation)_

---

@marithpl however, reported that lights may turn on after long periods by themselves.

I've seen this with one device integration too: Yeelight, but even with adaptive lighting turned off.

Can you turn off adaptive lighting for longer periods and see if the lights turn on by themselves still? It may not be related to adaptive lighting itself, but for example with short power outages which do trigger the "default light on" automatic inside the lights.

**Comment by RubenKelevra** [comment] 2022-06-15 02:32
Woopsi, I think I got lost in the translation. So yes, this is on the roadmap and will be fixed. :)

**Comment by basnijholt** [comment] 2022-11-20 18:50
**This is actually a duplicate of #85.

Please post new findings or debugging logs there.**

Using the logs is really the only way that I can debug this. I would need to see what the logs say exactly when the lights were turned on. Please post the logs from when it happened and just before it.

See https://github.com/basnijholt/adaptive-lighting/blob/master/README.md#having-problems

**Closed by basnijholt** 2022-11-20 18:50 UTC
Labels: kind/bug, need/triage, moved to v2 roadmap
