### ISSUE TITLE
Checkboxes in UI config for `min`/`max`/`sleep_brightness` don't do anything

### ISSUE THREAD

**Issue by ScottG489** [basnijholt/adaptive-lighting#315] opened 2022-08-27 04:33 UTC
#### Version information:
1.0.15

#### Description:
I was hoping to use them to control whether or not the integration controls those things, but it doesn't seem like the checkboxes do anything.

They should either match up with the state of the corresponding switch entities or just be removed from the configuration.

**Comment by basnijholt** [comment] 2022-08-28 18:05
When they are turned off the default settings are used.

**Comment by basnijholt** [comment] 2022-08-28 19:30
This is not configurable and build into HA.

**Comment by basnijholt** [comment] 2022-08-29 15:55
I closed this because the issue is with `home-assistant/core`, we have no control over that interface.

**Comment by ScottG489** [comment] 2022-08-29 16:22
Doesn't this integration control what inputs show up in the config window? I'm using other integrations whos config window has sliders for numbers which don't have a checkbox next to them.

**Comment by basnijholt** [comment] 2022-08-29 16:49
I have now verified that this issue also exists in `core`.

For example the `buienradar` integration (Minutes to look ahead for precipitation forecast):

<img width="373" alt="image" src="https://user-images.githubusercontent.com/6897215/187252305-a37260ce-fc47-4042-af46-bb173d7a4fb0.png">

This seems to be how Home Assitant renders options like `vol.All(vol.Coerce(int), vol.Range(min=min_int, max=max_int))`.

I recommend posting this issue here https://github.com/home-assistant/core/issues

Thanks for taking the time to report this here anyway!

**Closed by basnijholt** 2022-08-29 16:49 UTC
Labels: kind/bug, need/triage
