### ISSUE TITLE
Transition turn off

### ISSUE THREAD

**Issue by dankarization** [basnijholt/adaptive-lighting#420] opened 2023-01-24 04:48 UTC
I have a few lights that does not support transition at all- they just throw an error when trying to apply even 0 valued transition, therefore the component doesn't work at all. For now- there's no option to turn off transitions in the component at all, but this is much needed!

**Comment by karaminder** [comment] 2023-03-02 05:12
Agreed. I'm getting a ton of errors in my z2m logs stating:

`error 2023-03-01 20:49:29: No converter available for 'transition' (45)`

The debug log from z2m says:
'Received MQTT message on 'zigbee2mqtt/Hallway Above Cabinet Lights/set' with data '{"state":"ON","**transition":45.0**,"brightness":87,"color_temp":370}'

I wonder if the decimal point for the transition time is new?

(I hope this is not considered hijacking this thread. Happy to make a separate post if need be.)

**Comment by th3w1zard1** [comment] 2023-03-12 21:42
@karaminder can you post the raw json for your light? You can find that by going to your zigbee2mqtt frontend and looking at the devices 'state' tab.

While you're at it, can you post your devices.yaml file please?

**Comment by th3w1zard1** [comment] 2023-03-23 09:43
Duplicate of #378

**Closed by th3w1zard1** 2023-03-23 09:43 UTC
Labels: duplicate
