### ISSUE TITLE
Not working on 2021.05b

### ISSUE THREAD

**Issue by joselito11** [basnijholt/adaptive-lighting#110] opened 2021-04-29 05:03 UTC
Logger: homeassistant.components.switch
Source: custom_components/adaptive_lighting/switch.py:1021 
Integration: Stikalo (documentation, issues) 
First occurred: 6:50:45 (6 occurrences) 
Last logged: 6:56:25

Error adding entities for domain switch with platform adaptive_lighting
Error while setting up adaptive_lighting platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 558, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 580, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/adaptive_lighting/switch.py", line 604, in async_added_to_hass
    await self.async_turn_on(adapt_lights=not self._only_once)
  File "/config/custom_components/adaptive_lighting/switch.py", line 693, in async_turn_on
    await self._update_attrs_and_maybe_adapt_lights(
  File "/config/custom_components/adaptive_lighting/switch.py", line 821, in _update_attrs_and_maybe_adapt_lights
    self._settings = self._sun_light_settings.get_settings(
  File "/config/custom_components/adaptive_lighting/switch.py", line 1110, in get_settings
    percent = self.calc_percent()
  File "/config/custom_components/adaptive_lighting/switch.py", line 1073, in calc_percent
    today = self.relevant_events(now)
  File "/config/custom_components/adaptive_lighting/switch.py", line 1061, in relevant_events
    events = [
  File "/config/custom_components/adaptive_lighting/switch.py", line 1062, in <listcomp>
    self.get_sun_events(now + timedelta(days=days)) for days in [-1, 0, 1]
  File "/config/custom_components/adaptive_lighting/switch.py", line 1021, in get_sun_events
    location.sunrise(date, local=False)
AttributeError: 'tuple' object has no attribute 'sunrise'

**Comment by adamrutt** [comment] 2021-04-29 05:14
Same here, looks to be linked with [Update to Astra 2.2](https://github.com/home-assistant/core/pull/48573)

**Comment by bouwew** [comment] 2021-04-30 06:34
Same here, rolling back to HA Core 2021.4.6

**Comment by pixeye33** [comment] 2021-04-30 08:39
i was looking for a way to fix the issue, but instead found a way to circumvent it :

if a sunrise_time and sunset_time is defined in adaptive_lighting config the error can't happen anymore thanks to this : https://github.com/basnijholt/adaptive-lighting/blob/master/custom_components/adaptive_lighting/switch.py#L1022

i think the root cause is around the elevation

**Comment by basnijholt** [comment] 2021-04-30 08:49
I believe (untested) that https://github.com/basnijholt/adaptive-lighting/commit/b5eed585caf1264d47bea2af574803b7935b811e should fix it.

**Comment by basnijholt** [comment] 2021-04-30 09:03
I just tested it and it works now!

It just required on other fix (https://github.com/basnijholt/adaptive-lighting/commit/20a37b41035fc38c470ea611777fe7d962a05512).

**Comment by pixeye33** [comment] 2021-04-30 09:15
I confirm that it now works again, thanks for your quick fix !

**Comment by basnijholt** [comment] 2021-04-30 11:55
I'll close this issue then :)

**Closed by basnijholt** 2021-04-30 11:55 UTC
