### ISSUE TITLE
WLED light is not turning off properly if AL is enabled

### ISSUE THREAD

**Issue by d-dsn** [basnijholt/adaptive-lighting#251] opened 2022-02-03 09:44 UTC
#### Version information:
Version 1.0.15

#### Description:
I'm having WLED light with SK6812 (WWA color configuration). If the Adaptive Lighting component is on, and has been on for a few minutes(?), it sometimes becomes hard to switch the light off from HA by (light.turn_off) because the WLED light goes into somekind of a flicked-state where it gradually fades to off by flickering. When doing the off-flickering, if I immediately command "turn_on" and "turn_off" again, it turns off.

 This is my AL-config and I'm adapting to both colour and brightness:

```
- name: "Akustiikkataulu"
    lights:
    - light.akustiikkataulu
    prefer_rgb_color: false
    transition: 45
    initial_transition: 1
    interval: 90
    min_brightness: 3
    max_brightness: 50
    min_color_temp: 1500
    max_color_temp: 5000
    sleep_brightness: 1
    sleep_color_temp: 2000
#    sunrise_time: "09:00:00"  # override the sunrise time
    sunrise_offset: -1600
#    sunset_time: "13:00:00"
#    sunset_offset: '01:00:00'
    take_over_control: true
    detect_non_ha_changes: true
    only_once: false
```

**Comment by Elijen** [comment] 2022-02-14 00:02
Same issue here. Seems like the automation turns on the bulb accidentally on refresh even though it was just turned off.

**Comment by ikaruswill** [comment] 2022-02-22 17:07
I have the same issue. Currently on Home-Assistant docker `2022.2.8` I have Xiaomi Aqara lights controlled via `zigbee2mqtt`, the bulb seems to flicker when turning on or off. The issue is probably not related to the bulb we use but more likely related to some API changes with home-assistant in recent versions.

While observing the logs, I got this, might help anyone who's working on this issue.
```
2022-02-22 17:03:52 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
 File "/config/custom_components/adaptive_lighting/switch.py", line 1257, in turn_on_off_event_listener
 entity_ids = cv.ensure_list_csv(service_data[ATTR_ENTITY_ID])
KeyError: 'entity_id'
```

**Comment by jamescadd** [comment] 2022-03-05 17:52
There is a setting for change speed/delay or similar that you can set to 0 that I think would minimize this.

**Comment by basnijholt** [comment] 2022-08-30 17:56
@ikaruswill, are you using areas by any chance?

**Comment by ikaruswill** [comment] 2022-08-31 04:50
Hmm nope I'm not using areas.

**Comment by th3w1zard1** [comment] 2023-03-23 16:55
@ikaruswill @d-dsn @Elijen  Seems like an issue with `take_over_control` and/or `detect_non_ha_changes`. Could you enable debugging and post logs after reproducing this issue?

**Comment by basnijholt** [comment] 2023-08-06 20:31
This issue should have been addressed in recent releases. Please open a new issue (with logs) if you are still encountering this problem 😄

**Closed by basnijholt** 2023-08-06 20:31 UTC
Labels: kind/bug, need/author-input
