### ISSUE TITLE
One light turning on again after turning off the group

### ISSUE THREAD

**Issue by Kurisudes** [basnijholt/adaptive-lighting#410] opened 2022-12-22 09:10 UTC
#### Version information:
V1.4.1

#### Description:
On light turns back on again after turning off a group of zigbee lights (not a ZHA group but a group helper).

I get this if I listen to call_service:
Event 11 fired 9:58 AM:
event_type: call_service
data:
  domain: light
  service: turn_on
  service_data:
    entity_id: light.bedroom_light_bulb_1_level_light_color_on_off
    transition: 10
    brightness: 255
    color_temp_kelvin: 4000
origin: LOCAL
time_fired: "2022-12-22T08:58:36.535368+00:00"
context:
  id: adapt_lgt:b'*Xx`':interval:b'6%q'
  parent_id: null
  user_id: null

Event 9 fired 9:58 AM:
event_type: call_service
data:
  domain: light
  service: turn_off
  service_data:
    entity_id:
      - light.bedroom_light_bulb_1_level_light_color_on_off
      - light.bedroom_light_bulb_2_level_light_color_on_off
      - light.bedroom_light_bulb_3_level_light_color_on_off
origin: LOCAL
time_fired: "2022-12-22T08:58:31.689347+00:00"
context:
  id: 01GMWGWEBVZNCBWVF07F8S6AFR
  parent_id: 01GMWGWEBM53FTCQC1CPFV2ERG
  user_id: null

Event 8 fired 9:58 AM:

**Comment by matthiasradecke** [comment] 2023-01-17 08:34
same is happening to me. random lights turn on back again after they are turned off by an automation. only happens sometimes. I already increased the update interval to 300 seconds and that makes it happen less often, but is still annoying to realize that the bedroom lights have been on for hours.

**Comment by matthiasradecke** [comment] 2023-01-17 08:41
btw it does not happen when only_once is activated, which at least solved the problem for lights that don't stay on for long (like in the hallway). So it must be that the lights get updated with new values although they are already off (and state is showing off in HA)

**Comment by foulk466** [comment] 2023-01-25 19:40
I have the same issue as mentioned above on version 1.4.1

Using an automation to turn off the lights, some of them turn on again (Not using groups, individual lights only)
If only_once activated it also fixes my issue.

History of the light that turn on again:

turned on triggered by service light.turn_on
2:31:16 PM - 2 minutes ago
turned off triggered by automation ****
triggered by state of Switch
2:30:54 PM - 3 minutes ago
turned on triggered by automation ****
triggered by state of Switch
2:29:22 PM - 4 minutes ago

**Comment by bluecube22** [comment] 2023-02-03 17:23
Looks like a duplicate of https://github.com/basnijholt/adaptive-lighting/issues/377

In the Adaptive Lighting configuration, try setting `interval` to smaller value than `transition` and `sleep_transition` and restarting Home Assistant.

**Comment by nickdos** [comment] 2023-03-01 09:27
I'm seeing this issue and I've tried the recommended settings from #377 but it did not fix anythingfor me. I've tried several variations, including using the exact values in the screenshot from that issue. 

My situation is specific to this issue, in that I'm experiencing this with Zigbee lights in a group. In my case the group is defined by the deCONZ system.

**Comment by th3w1zard1** [comment] 2023-03-12 21:45
Can someone experiencing this on zigbee2mqtt post their configuration.yaml and devices.yaml so I can reproduce your settings?

**Comment by filikun** [comment] 2023-03-27 19:52
I have had similar issues and for me it was the Z2M zigbee groups. Moving to HA groups removed the problem completely.

**Comment by filikun** [comment] 2023-03-27 20:13
> Can someone experiencing this on zigbee2mqtt post their configuration.yaml and devices.yaml so I can reproduce your settings? Your adaptive-lighting config is also needed.
> 
> I was getting this issue with older configurations - using zigbee2mqtt. I was only able to solve this accidentally by updating everything to the latest version. I also redid the zigbee2mqtt configuration.yaml just to be certain everything would act the way I wanted it to. `optimistic` was very significant in my tests I remember.

I just tried reproducing it and got the issue right away. Here are my files.

[devices.zip](https://github.com/basnijholt/adaptive-lighting/files/11082598/devices.zip)

<details>
<summary>Pictures on the adaptive config</summary>
![image](https://user-images.githubusercontent.com/9947929/228055463-20eb54bd-5bf5-40af-84b8-073c0e137d86.png)

![image](https://user-images.githubusercontent.com/9947929/228055480-5976adec-2866-4e91-b222-d0875885a12f.png)
</details>

**Comment by th3w1zard1** [comment] 2023-03-27 20:30
@filikun can you post debug logs of this happening? Set your interval low and you should notice the problem right away.
I use optimistic: true on my configuration: I couldn't get optimistic: false to work. When optimistic is false it would never publish any state changes to HA which adaptive-lighting relies on.

**Comment by filikun** [comment] 2023-03-27 20:33
Yeah, I'll revert my optimistic change and turn on the logs. Give me a moment

**Comment by th3w1zard1** [comment] 2023-03-27 20:34
Set your interval to something like 5 as well.

**Comment by filikun** [comment] 2023-03-27 20:36
> 

Hmm how can I cahnge the interval?

**Comment by filikun** [comment] 2023-03-27 20:43
Anyhow here is something. So I played around a little applying adaptive, taking it away, adding it again and applying night mode and turning on and off some individual lights. Not spamming them but a slow "stress" test and had some issues right away.

https://pastebin.com/u1xg9rsK

**Comment by th3w1zard1** [comment] 2023-03-27 20:46
> > 
> 
> Hmm how can I cahnge the interval? And is there a way to isolate the logs from the logger integration? It's a lot going on here

Go to home assistant's integrations page. Should look like this:
![image](https://user-images.githubusercontent.com/2219836/228062370-41bdd856-b141-4581-b9ee-f9f4673a2764.png)

Click adaptive-lighting to see the following:
![image](https://user-images.githubusercontent.com/2219836/228062576-36f57ae8-98b3-403e-be0b-a81dad362431.png)

**Comment by filikun** [comment] 2023-03-27 20:57
@th3w1zard1 

Alright! Here we go https://pastebin.com/5NQZRMfK

**Comment by filikun** [comment] 2023-03-28 04:44
@th3w1zard1  

Did you find anything useful?

**Comment by th3w1zard1** [comment] 2023-03-30 19:24
@filikun Sorry for the delay, haven't had much time to look into this.

For reference I see your group is composed of the following:

```
Lampa sovrum fönster 4
Lampa sovrum säng Filip 16
Lampa sovrum säng Hannah 17
Lampa sovrum skrivbord Filip 1
Lampa sovrum skrivbord Hannah 2
Lampa sovrum tak 6
```

Do you know if it's always the same bulb in the group everytime that is getting turned on?

I wasn't able to find anything useful in your logs, but there's a lot in there and I haven't had time to properly go line by line.


Is there perhaps anything useful in your logbook?
![image](https://user-images.githubusercontent.com/2219836/228942207-f627a5d8-ca0d-459b-89fe-a189884e3a02.png)

I have one more idea on how to test this but I'll need some time to write the automation.

**Comment by th3w1zard1** [comment] 2023-03-30 19:44
@filikun I'm sorry I just need more information. I've created a script with the exact light.turn_on calls adaptive lighting is using from your posted logs. Can you run this script with your same group and see if you get the same issue? Make sure to turn off adaptive-lighting or disable it before running this.

```yaml
alias: Stress test zigbee group
sequence:
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 144
      color_temp_kelvin: 2500
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 144
      color_temp_kelvin: 2500
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 144
      color_temp_kelvin: 2500
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 0
  - service: light.turn_on
    data:
      transition: 1
      brightness: 3
      color_temp_kelvin: 2202
    target:
      entity_id: light.den_ceilingfan_lights
mode: single
```

For the record I tried this on two different zigbee light groups I have and it worked fine.

**Comment by filikun** [comment] 2023-04-01 07:03
@th3w1zard1 
I'll try this out and get back to you ASAP!

**Comment by filikun** [comment] 2023-04-01 07:24
It didn't do much log wise 

```yaml
2023-04-01 09:19:08.373 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Sovrum: Called '_setup_listeners'
2023-04-01 09:19:08.373 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Sovrum: Cancelled '_setup_listeners'
```

**Comment by th3w1zard1** [comment] 2023-04-01 07:25
@filikun the script I posted were the exact same light.turn_on calls that adaptive-lighting did in your logs you posted earlier. So the question is after you ran the script, did any of your bulbs become unsynced?

**Comment by th3w1zard1** [comment] 2023-04-01 07:27
Please check https://github.com/basnijholt/adaptive-lighting/issues/410#issuecomment-1490820625 in case you missed it.

**Comment by filikun** [comment] 2023-04-01 07:34
Hmm no nothing ordinary. It might be that I'm using the light group in AL and then was turning of one of the grouped lights and thinking that if it's off then it won't turn back on but if AL sends a light ON to the whole group every light would be expected to turn on. 

Everything was in sync during the test. I will have to take AL live and make sure to have smaller light groups in my areas as I don't want all lights to always be on in a room. 

My stupidity obviously, sorry for taking your time! I know I had problems with AL turning on lights at random before (not the same case as the one I described here) I'll have to see if works.

**Comment by th3w1zard1** [comment] 2023-04-01 07:37
No worries! please don't hesitate to post back here if you find out more info we can debug

**Comment by filikun** [comment] 2023-04-01 10:29
@th3w1zard1 one more thing. I have now created some light groups. I have one for the entire room, one for roof lights, one for windows and one for task lights. 4 in total and the one for the entire room contains all lights. When I turn on one individual light, every light in the room turns on. Is that expected?

**Comment by filikun** [comment] 2023-04-01 10:31
All lights group
light.a
light.b
light.c
light.d
light.e

Roof group
light.a
light.b

Window group
light.c
light.d

Task group
light.e

Turning on one light, light.e, turns on all above lights

**Comment by th3w1zard1** [comment] 2023-04-01 14:27
@filikun if one light is turning on your whole group, you need to disable optimistic _inside the group itself_

**Comment by protyposis** [comment] 2023-05-08 19:25
I use Adaptive Lighting with Zigbee2MQTT and Ikea Tradfri bulbs. I sometimes get odd behavior of individually controlled single lights (not groups!) staying on despite after being turned off and also being reported as off.

When it happens, HA reports them off, and Z2M reports them off, but they are shining. When I manually sync the state in Z2M, it correctly updates to the on-state. I don't know whether they just stay on, or immediately turn back on after being turned off. It happens only every once in a while, and I haven't found a way to reproduce, so I just could have missed the off/on sequence.

It seems like this doesn't happen during the day, only during adjustment phases in the morning and at night, but I'm not 100% sure on that either. My theory is that AL adjustment commands might interfere with turn-off commands. `interval` is set to the default 90 seconds, and I feel like whatever I set it to, it's either too long and counteracts the purpose of AL, or there's a chance that commands collide.

Anyway, I'm primarily wondering whether this is the same issue as reported here?

**Comment by protyposis** [comment] 2023-05-09 09:34
I have now also witnessed my lights turning back on, and I figured out the reason. It happens since I enabled `separate_turn_on_commands` and it's because this split command sequence isn't cancelled when a light is turned off.

This is the problematic code (the `else` branch):
https://github.com/basnijholt/adaptive-lighting/blob/9caf64509349958a340f8cef9207fdb0ea35dbef/custom_components/adaptive_lighting/switch.py#L1203-L1216

And here is a Zigbee2MQTT log which demonstrates it nicely:
```
// Light turn-on command
Debug 2023-05-09 10:57:11 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON"}'

// AL responds to turn-on with split adaptation commands (separate color temperature and brightness)
Debug 2023-05-09 10:57:11 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5,"color_temp":250}'
Debug 2023-05-09 10:57:13 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5,"brightness":254}'

// Later, AL sends a scheduled adapation command (first half of split: color temperature)
Debug 2023-05-09 10:57:27 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":22.5,"color_temp":250}'

// Then, the light is turned off
Debug 2023-05-09 10:57:33 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"OFF"}'

// NOW THE PROBLEM:
// AL sends the second half (brightness) of the adaptation command initiated before the light was turned off
Debug 2023-05-09 10:57:50 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":22.5,"brightness":254}'

// UNDESIRED SIDE EFFECT:
// AL thinks the light was regularly turned on and sends another split adaptation command
Debug 2023-05-09 10:57:51 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5,"color_temp":250}'
Debug 2023-05-09 10:57:52 Received MQTT message on 'zigbee2mqtt/Bulb01/set' with data '{"state":"ON","transition":0.5,"brightness":254}'
```

To fix the lights turning back on, the split command sequence needs to be cancelled when the lights are turned off.

This seems to be related to the issue described in my previous comment https://github.com/basnijholt/adaptive-lighting/issues/410#issuecomment-1538922312 where the lights just stay on. The difference is that there, a scheduled adjustment command collides with and overrules the turn-off command. This race condition can happen with and without `separate_turn_on_commands`, it's just less likely.

**Closed** 2023-05-21 17:36 UTC
Labels: kind/bug, need/author-input
