### ISSUE TITLE
Controlling one bulb in a ZHA light group affects all the bulbs in the group

### ISSUE THREAD

**Issue by daFreeMan** [basnijholt/adaptive-lighting#345] opened 2022-09-30 15:55 UTC
#### Description:
I have Zigbee bulbs, and have defined an `Office Light Fixture` containing 4 bulbs using the ZHA integration's `Groups` feature.

After sunset/before sunrise if I walk into the office, I only want one single bulb to turn on dimly to provide just enough light to see by, so I have a "night light" automation to turn on just one bulb:
```YAML
- id: '1642161608570'
  alias: Office lights on when occupied - night light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.office_sensor_motion_aq2_ias_zone
    to: 'on'
    from: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: or
    conditions:
    - condition: sun
      before: sunrise
      before_offset: '30:00'
    - condition: sun
      after: sunset
      after_offset: '-30:00'
  action:
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: light.office_light_fixture
      manual_control: true
  - service: light.turn_on
    target:
      entity_id: light.office_bulb_1
    data:
      transition: 30
      kelvin: 2700
      brightness: 1
  mode: single
```

This works great so long as I do _not_ have any of the 4 office bulbs or the office light group configured to be controlled by AL. As soon as I add them to the AL config, all 4 bulbs will turn on at whatever the AL configured brightness level is, which is always too bright first thing in the morning...

**Comment by HStep20** [comment] 2022-11-13 19:09
Ive been seeing this behavior as well. I will turn on one light, and all the lights in a room will come on, or I turn on the Kitchen Lights, and all the lights come on in the house because of the 'all lights' group. 

I wouldn't have connected it to groups, but Im glad theres a workaround to avoid it for the moment.

**Comment by nathang21** [comment] 2022-12-12 14:01
I think this is a dupe of #304 (not specific to Zigbee lights), I'm seeing this behavior with multiple types of lights, primarily with various types of groups (autogenerated room groups, or manually created HA groups etc).

**Comment by ASNNetworks** [comment] 2022-12-19 22:45
This is because the way group works  in Home Assistant is if ANY of the members is on, the group entity is also shown as on in Home Assistant. So therefore, adaptive light will adapt the group light (since that entity is on), which in turn will turn on all its members since the group entity changed the brightness.

If you created a light group withing Home Assistant itself, you can change this behavior so that the group entity is only on when ALL members are on. This is explained here: https://www.home-assistant.io/integrations/group/#all

If you have created the group using Zigbee (like ZHA or Z2M groups) then I don't think this is possible.

**Comment by daFreeMan** [comment] 2022-12-20 14:06
Thanks, @ASNNetworks, that's helpful info.
My workaround was to update my automation to turn AL off so that I can turn on a single bulb, then later, when I'm ready for more light, another automation turns AL back on.

**Comment by th3w1zard1** [comment] 2023-03-22 05:23
@ASNNetworks described the problem very well.

>If you have created the group using Zigbee (like ZHA or Z2m groups) then I don't think this is possible.

All you have to do in Z2M is set `optimistic: false` in the `groups.yaml` file for the light to solve this.

**Closed** 2023-03-23 10:09 UTC
