### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable (again)

### ISSUE THREAD

**Issue by mrplow** [basnijholt/adaptive-lighting#63] opened 2020-12-27 00:10 UTC
I seem to be having a similar issue as #46. I'm not sure if I should be updating #46 or creating a new one.

I've installed 008c5e4 of this component via HACS and was able to set it up nicely, have a sleep automation setup and all is well except the reset manual control example automation (I changed it to 5 min for testing):
```
alias: 'Adaptive lighting: reset manual_control after 1 hour'
trigger:
  - platform: event
    event_type: adaptive_lighting.manual_control
action:
  - delay: '00:00:05'
  - condition: template
    value_template: '{{ light in state_attr(''switch'', ''manual_control'') }}'
  - service: adaptive_lighting.set_manual_control
    data:
      entity_id: '{{ switch }}'
      lights: '{{ light }}'
      manual_control: false
mode: parallel
max: 200
variables:
  light: '{{ trigger.event.data.entity_id }}'
  switch: '{{ trigger.event.data.switch }}'
```

configuration.yaml:
```
adaptive_lighting:
  lights:
    - light.globe1_globe1
    - light.globe2_globe2
    - light.bathroom_light
    - light.dans_bedside_lamp
    - light.mollys_bedside_lamp
    - light.fan_light
    - light.kitchen_chandelier
```

Listening to adaptive_listing.manual_control I do see the switch being defined
```
{
    "event_type": "adaptive_lighting.manual_control",
    "data": {
        "entity_id": "light.globe1_globe1",
        "switch": "switch.adaptive_lighting_default"
    },
    "origin": "LOCAL",
    "time_fired": "2020-12-26T23:55:18.534980+00:00",
    "context": {
        "id": "7da8bb422b7f6dc7617742c96b17a14c",
        "parent_id": null,
        "user_id": "248eec6876d24ee4bf75a823ec66ce75"
    }
}
```

Below is my relevant home-assistant.log
```
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] default: '_update_attrs_and_maybe_adapt_lights' called with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Adaptive Lighting: default: '_adapt_lights(['light.kitchen_chandelier', 'light.globe1_globe1', 'light.dans_bedside_lamp', 'light.mollys_bedside_lamp', 'light.bathroom_light', 'light.fan_light', 'light.globe2_globe2'], None, force=False, context.id=adapt_lgt_7505_interval_32)' called
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] default: Scheduling 'light.turn_on' with the following 'service_data': {'entity_id': 'light.kitchen_chandelier', 'transition': 45.0, 'brightness': 255, 'color_temp': 353} with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] 'adaptive_lighting.manual_control' event fired for switch.adaptive_lighting_default for light light.globe1_globe1
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] 'light.globe1_globe1' was already on and 'light.turn_on' was not called by the adaptive_lighting integration (context.id='7da8bb422b7f6dc7617742c96b17a14c'), the Adaptive Lighting will stop adapting the light until the switch or the light turns off and then on again.
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] default: 'light.globe1_globe1' is being manually controlled, stop adapting, context.id=adapt_lgt_7505_interval_32.
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] default: Scheduling 'light.turn_on' with the following 'service_data': {'entity_id': 'light.dans_bedside_lamp', 'brightness': 255, 'white_value': 255, 'color_temp': 353} with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] default: Scheduling 'light.turn_on' with the following 'service_data': {'entity_id': 'light.mollys_bedside_lamp', 'transition': 45.0, 'brightness': 255, 'color_temp': 353} with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.kitchen_chandelier']')' event with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.dans_bedside_lamp']')' event with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected an 'light.turn_on('['light.mollys_bedside_lamp']')' event with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.mollys_bedside_lamp' 'state_changed' event: '{'min_mireds': 153, 'max_mireds': 454, 'brightness': 255, 'color_temp': 353, 'friendly_name': "Molly's bedside lamp", 'supported_features': 43}' with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.kitchen_chandelier' 'state_changed' event: '{'min_mireds': 153, 'max_mireds': 454, 'brightness': 255, 'color_temp': 353, 'friendly_name': 'Kitchen chandelier', 'supported_features': 43}' with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:18 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.dans_bedside_lamp' 'state_changed' event: '{'min_mireds': 153, 'max_mireds': 500, 'effect_list': ['0', '1', '2', '3', '4'], 'brightness': 255, 'color_temp': 353, 'white_value': 255, 'effect': '0', 'friendly_name': "Dan's bedside lamp", 'supported_features': 151}' with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:23 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.kitchen_chandelier' 'state_changed' event: '{'min_mireds': 153, 'max_mireds': 454, 'brightness': 255, 'color_temp': 349, 'friendly_name': 'Kitchen chandelier', 'supported_features': 43}' with context.id='adapt_lgt_7505_interval_32'
2020-12-26 15:55:23 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] State change event of 'light.kitchen_chandelier' is already in 'self.last_state_change' (adapt_lgt_7505_interval_32) adding this state also
2020-12-26 15:55:23 ERROR (MainThread) [homeassistant.helpers.condition] Error during template condition: TypeError: argument of type 'NoneType' is not iterable
2020-12-26 15:55:28 DEBUG (MainThread) [custom_components.adaptive_lighting.switch] Detected a 'light.mollys_bedside_lamp' 'state_changed' event: '{'min_mireds': 153, 'max_mireds': 454, 'brightness': 255, 'color_temp': 349, 'friendly_name': "Molly's bedside lamp", 'supported_features': 43}' with context.id='5bb0fe18e130aadb8d52724e2794b6ee'

```

**Comment by basnijholt** [comment] 2020-12-27 12:11
Hi @mrplow,

Thanks for giving this component a try!

The problem is in your condition:
```yaml
    value_template: '{{ light in state_attr(''switch'', ''manual_control'') }}'
```
which should be
```yaml
    value_template: '{{ light in state_attr(switch, ''manual_control'') }}'
```

I will close this issue as I am 99.9% sure it's fixed when making that change.

Please let me know if that is not the case and I will reopen this issue.

**Closed by basnijholt** 2020-12-27 12:11 UTC

**Comment by mrplow** [comment] 2020-12-28 00:43
Yup that fixed it, thanks @basnijholt 

At first I thought it wasn't working. But I was testing with a 5 second delay, not 5 minutes lol
