### ISSUE TITLE
Change state while light off

### ISSUE THREAD

**Issue by mekenthompson** [basnijholt/adaptive-lighting#76] opened 2021-01-12 11:58 UTC
Is it possible to change the state while the light is off?

I'm assuming this is making changes to state when it sees the light turn on/off, but what I would like is for the adaptive lighting to change state of the light while the light is off - so there is no delay in transition when turned on. I've tried setting the interval to 0, but the light still turns on with prior temp and then instantly changes to the new adaptive temperature with no transition (Which I've subsequently found at that variable I was changing controls; transition timeframe). 

Maybe this isn't possible for all lights which require you to change colour on state change? I believe LIFX integration allows this (Changing colour/brightness even while "off"), but not sure if all lights do? https://www.home-assistant.io/integrations/lifx/#set-state. I'm running LIFX so would love to know how to achieve this.

**Comment by kreene1987** [comment] 2021-01-26 17:08
Will add that my Inovelli LZW42's allow for color pre-staging and I was looking for this feature. Checkbox for color changing even while light is "off" would be amazing!

**Comment by jd1900** [comment] 2021-03-05 11:11
Using zigbee2mqtt it is possible in zigbee lights. 
However, using HA GUI controls or default services I haven't found the option.

Is actually what I require in this issue: https://github.com/basnijholt/adaptive-lighting/issues/96

**Comment by Enf0** [comment] 2022-01-17 19:37
Has there been any further thoughts regarding this (and #96)? Right now, if I have turn on an AL-enabled light, it will first restore to its' previous brightness - as is standard for most lights/dimmers - before Adaptive Lighting kicks in a few seconds later to adjust the brightness. To me, this makes the integration feel not as "seamless" as I hope for.

I thought of an alternative implementation, which may or may not be feasible:
What if instead of using a normal `light.turn_on` action in our automations, Adaptive Lighting would provide its' own, i.e. `switch.adaptive_light_turn_on` which itself would trigger a `light.turn_on` service call with the appropriate `brightness_pct`.

Would something like this make sense?

**Comment by mekenthompson** [comment] 2023-03-27 20:11
@th3w1zard1 - Do you have any docs/guidance on how to achieve the objective of this issue with the new PR?

The primary use case I was looking to achieve, was for:
- A light is switched off
- Sleep mode is turned on
- The rgb/brightness is updated in light settings; especially when on sleep mode
- When the light is turned on, it is already at the correct rgb/brightness and has no transition from previous state when on, to new state

ie. Walk into a room (most of my lights are motion sensor activated) in the middle of the night, and you aren't blinded for a short period with a bright light while it adjusts to sleep mode.

I've had a test with just normal sleep mode and it doesn't achieve the objective; do I have to set up a new configuration / trigger one of these new adapative switch entities via automation - instead of leveraging sleep mode switch?

**Comment by kreene1987** [comment] 2023-03-27 20:27
> @th3w1zard1 - Do you have any docs/guidance on how to achieve the objective of this issue with the new PR?
> 
> The primary use case I was looking to achieve, was for:
> 
> * A light is switched off
> * Sleep mode is turned on
> * The rgb/brightness is updated in light settings; especially when on sleep mode
> * When the light is turned on, it is already at the correct rgb/brightness and has no transition from previous state when on, to new state
> 
> ie. Walk into a room (most of my lights are motion sensor activated) in the middle of the night, and you aren't blinded for a short period with a bright light while it adjusts to sleep mode.
> 
> I've had a test with just normal sleep mode and it doesn't achieve the objective; do I have to set up a new configuration / trigger one of these new adapative switch entities via automation - instead of leveraging sleep mode switch?

Do your lights support pre-staging? Can you do this manually via color change while off and it comes on with new color?

**Comment by th3w1zard1** [comment] 2023-03-28 15:49
@mekenthompson The problem is HASS doesn't know what a light's brightness was while it's off, so it just tells it to turn on. Only your lightbulb knows what it was last at so you'd need to configure its power on state i'd imagine.

I'm sorry I closed this issue as I can see now it's very much still a problem after a quick test.

**Comment by th3w1zard1** [comment] 2023-03-29 20:57
I'm stumped on this one. 
![image](https://user-images.githubusercontent.com/2219836/228665333-c67c0b31-af66-4f2c-8fe0-e1ea73fd9ca5.png)

So basically adaptive-lighting doesn't do anything with the bulb while it's off or even when it turns on. It _updates_ the bulb on every `interval`. So you'd need to configure your automation to turn your light on to 1% brightness, then adaptive-lighting can do the rest on its next interval.

**Comment by mekenthompson** [comment] 2023-03-29 21:11
Yeah, guess I could set up two automation for turning lights on that are in sleep mode and have them on conditional times. Does adaptive lighting on those intervals store the brightness/temp as variables so that I could pass these into the light on service call?

**Comment by th3w1zard1** [comment] 2023-03-29 21:13
I think you're overthinking it: you said you had your lights on a motion sensor that turns them on right? So I assume you have an automation that looks for the sensor to read true and then fires `light.turn_on`. In that very same call, just have brightness: 1 in the payload.

**Comment by mekenthompson** [comment] 2023-03-29 22:18
True, I'll try setting at 1 and see how that works. 

Although, It looks like I can get the brightness from the adaptive light switch attributes, so I will try also passing that through as a template variable into the light turn on also.

**Comment by th3w1zard1** [comment] 2023-03-30 01:04
No that's not what I said. Set `brightness_pct` in the **_actual light.turn_on call_**. You have a motion sensor turning your lights on already, just set `brightness_pct` in that `light.turn_on` call.

Something like:
\> condition: motion:
\> _**service: light.turn_on**_
\> data:
\>    brightness_pct: 1

That's it.

**Comment by mekenthompson** [comment] 2023-03-30 08:02
Yeah, I totally got what you were recommendig 😀. Which was certainly a simple and great solution, so thanks!

But the perfectionist in me would like it to turn on without any transition, so passing through those actual variables (including kelvins) get's exactly what I want.

Either way, thanks for the steer in the right direction, problem solved 🙂 👍

**Closed** 2023-03-30 08:02 UTC
Labels: need/triage, kind/enhancement, need/team-effort-estimate, related-to-v1

**Comment by AJolly** [comment] 2024-09-16 04:58
I'd prefer to reopen the issue - I expected adaptive lighting to handle changing light color/brightness even when a light was off (for lights that support it, ie - lifx).  

The current workarounds rely on intercepting a light turn on command, which requires HA to be in charge of turning on the light.
